name: Pull Request

on:
  workflow_dispatch:

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install modules
        run: npm ci
      - name: unit tests
        run: npm run test-unit
